### ISSUE TITLE
space-separated list of hostnames doesn't work anymore

### ISSUE THREAD

**Issue by DanScharon** [lualdap/lualdap#10]
Hi,

I upgraded Prosody to 0.11 and to Lua 5.2. With mod_auth_ldap users can authenticate, but only if the option `ldap_server` consists of a single hostname or IP. A space-separated list of hostnames/IPs doesn't work anymore with lua-ldap 1.2.5 
Using a space-separated list of e.g. three hostnames leads to the following log entries when a user tries to authenticate:
```
Jan 15 01:19:15 xmpp-test.example.com:auth_ldap	warn 	LDAP: nil LuaLDAP: Error connecting to server (in reconnect)
Jan 15 01:19:15 xmpp-test.example.com:auth_ldap	warn 	LDAP: nil LuaLDAP: Error connecting to server (in reconnect)
Jan 15 01:19:15 xmpp-test.example.com:auth_ldap	warn 	LDAP: nil LuaLDAP: Error connecting to server (in reconnect)
Jan 15 01:19:15 xmpp-test.example.com:auth_ldap	error 	LDAP: LuaLDAP: Error connecting to server
Jan 15 01:19:15 c2s55e97c749000	info	Failed authentication attempt (not-authorized) for user xxxx from IP: xxx.xxx.xxx.xxx
```

When using the current version in master, the error message changes to:

```
Jan 16 11:22:17 xmpp-test.example.com:auth_ldap warn    LDAP: nil Bad parameter to an ldap routine (in reconnect)
Jan 16 11:22:17 xmpp-test.example.com:auth_ldap warn    LDAP: nil Bad parameter to an ldap routine (in reconnect)
Jan 16 11:22:17 xmpp-test.example.com:auth_ldap warn    LDAP: nil Bad parameter to an ldap routine (in reconnect)
Jan 16 11:22:17 xmpp-test.example.com:auth_ldap error   LDAP: Bad parameter to an ldap routine
```

Kind wishes,
Dan

**Comment by devurandom** [comment]
What was the last version of LuaLDAP this worked with? How did you install LuaLDAP?

**Comment by DanScharon** [comment]
Hi @devurandom , the last version of LuaLDAP it worked with was 1.1.0, the version that is available in Debian stretch via apt (1.1.0-1-geeac494-6+b2). This was in conjunction with Prosody 0.10 and Lua5.1.
After the upgrade to the LuaLDAP version in stretch-backports (1.2.5) it stopped working (in conjunction with Prosody 0.11 and Lua5.2). I then built an own deb package with the latest version in the github repo (8c05faf).

**Comment by DanScharon** [comment]
well, it's right in the manual: https://github.com/lualdap/lualdap/blob/8c05fafe7d7015994cdcd5f55766dde35babfc75/doc/us/manual.html#L159

**Comment by devurandom** [comment]
The manpage for OpenLDAP's `ldap_init` and `ldap_initialize` supports the LuaLDAP manual's claim:
> ldap_open() takes host, the hostname on which the LDAP server is running, and port, the port number to which to connect.  [...]  The host parameter may contain a blank-separated list of hosts to try to connect to, and each host may optionally by  of  the  form host:port. [...]
>
> ldap_init() acts just like ldap_open(), [...]
>
> ldap_initialize() acts like ldap_init(), [...]  The uri parameter may be a comma- or whitespace-separated list of URIs containing only the schema, the host, and the port  fields. [...]

LuaLDAP's regression was probably caused by the switch to OpenLDAP 2.3+ API in 141c0326283325963f689b48df5e6cd7d399da30 7 years ago, where `ldap://` is being prepended to the hostname in order to be able to use the new URI-based OpenLDAP API without breaking LuaLDAP API. Because of that, we will have to re-introduce the original behaviour with some new code in LuaLDAP.

@DanScharon could you please write a PR with tests for the three cases of host strings outlined in the OpenLDAP manpage (`host:port` whitespace separated, `uri` whitespace and comma separated)? I will then go and add the code to it that makes the tests pass.
